// export const SUBSCRIPTION_LIST_REQUEST = 'SUBSCRIPTION_LIST_REQUEST';
// export const SUBSCRIPTION_LIST_SUCCESS = 'SUBSCRIPTION_LIST_SUCCESS';
// export const SUBSCRIPTION_LIST_FAIL = 'SUBSCRIPTION_LIST_FAIL';

export const WORD_LIST_MY_REQUEST = 'WORD_LIST_MY_REQUEST';
export const WORD_LIST_MY_SUCCESS = 'WORD_LIST_MY_SUCCESS';
export const WORD_LIST_MY_FAIL = 'WORD_LIST_MY_FAIL';
export const WORD_LIST_MY_RESET = 'WORD_LIST_MY_RESET';

export const WORD_UPDATE_REQUEST = 'WORD_UPDATE_REQUEST';
export const WORD_UPDATE_SUCCESS = 'WORD_UPDATE_SUCCESS';
export const WORD_UPDATE_FAIL = 'WORD_UPDATE_FAIL';
export const WORD_UPDATE_RESET = 'WORD_UPDATE_RESET';

export const WORD_LIST_REQUEST = 'WORD_LIST_REQUEST';
export const WORD_LIST_SUCCESS = 'WORD_LIST_SUCCESS';
export const WORD_LIST_FAIL = 'WORD_LIST_FAIL';
export const WORD_LIST_RESET = 'WORD_LIST_RESET';

export const FAV_LIST_MY_REQUEST = 'FAV_LIST_MY_REQUEST';
export const FAV_LIST_MY_SUCCESS = 'FAV_LIST_MY_SUCCESS';
export const FAV_LIST_MY_FAIL = 'FAV_LIST_MY_FAIL';
export const FAV_LIST_MY_RESET = 'FAV_LIST_MY_RESET';

export const FAV_UPDATE_REQUEST = 'FAV_UPDATE_REQUEST';
export const FAV_UPDATE_SUCCESS = 'FAV_UPDATE_SUCCESS';
export const FAV_UPDATE_FAIL = 'FAV_UPDATE_FAIL';
export const FAV_UPDATE_RESET = 'FAV_UPDATE_RESET';

export const FAV_LIST_REQUEST = 'FAV_LIST_REQUEST';
export const FAV_LIST_SUCCESS = 'FAV_LIST_SUCCESS';
export const FAV_LIST_FAIL = 'FAV_LIST_FAIL';
export const FAV_LIST_RESET = 'FAV_LIST_RESET';
